### ISSUE TITLE
GPL 3.0 license for labels and side-loading of models

### ISSUE THREAD

**Issue by woheller69** [woheller69/whoBIRD#1]
@kahst 
As discussed a few minutes ago I changed the README, now saying that the BirdNET label files can be used under GPL3.0 license

Please confirm.

The BirdNET TFlite models will be moved to a different repo and downloaded by the app at first start in future to allow a publication of the app under GPL3.0 on F-Droid

**Comment by kahst** [comment]
Yes, the label files can be used under GPL3.0 - feel free to publish the app on F-Droid when side-loading the models.

**Comment by woheller69** [comment]
Side-loading is implemented. 
Models are loaded from  https://github.com/woheller69/whoBIRD-TFlite repository which has CC-BY-NC-SA 4.0 license.
This repository is now changed to GPLv3 and renamed to whoBIRD

Please try V1.4 to see the message displayed when downloading the model. I hope it is ok like this
