### ISSUE TITLE
change the entire UI to another language

### ISSUE THREAD

**Issue by XandrexOSM** [woheller69/whoBIRD#10]
hello, is it possible to allow the user to change the language of the entire app please? Maybe using Weblate?
I am interested for the French language, and I am already used to contribute to Weblate for other projects.

**Comment by woheller69** [comment]
Sure, just translate this file and upload it here.

https://github.com/woheller69/whoBIRD/blob/master/app/src/main/res/values/strings.xml

**Comment by XandrexOSM** [comment]
@woheller69 
I added an XML header to manage the accents.
[strings-FR-fr.xml.txt](https://github.com/woheller69/whoBIRD/files/14394474/strings-FR-fr.xml.txt)

**Comment by XandrexOSM** [comment]
but the names of the birds will remain in English?

**Comment by woheller69** [comment]
There is a French translation for bird names. If I set French as language, these are shown.

https://github.com/woheller69/whoBIRD/blob/master/app/src/main/assets/labels_fr.txt

**Comment by XandrexOSM** [comment]
How can I change the language to have french names? My phone is using Android 12.

**Comment by woheller69** [comment]
French should either be your default language in Android settings - languages. Or French should at least be on that list and select French in Android settings - apps - whoBIRD
