### ISSUE TITLE
RFE: add option to show scientific names

### ISSUE THREAD

**Issue by DuncanLithgow** [woheller69/whoBIRD#12]
I think it would be great to add option/default to show both common name for the current UI language and additionally scientific names in brackets.

Scientific names are more language independent and standardised. Adding scientific names would also be a good bridge for languages not available as a UI choice.

Great app! Exactly what I've been waiting the last few years.

**Comment by woheller69** [comment]
you can view the scientific name when viewing the pictures. Scroll the image up a bit. Below you will see the scientific name
