### ISSUE TITLE
An option to play preset bird sound from view section.

### ISSUE THREAD

**Issue by Baloe2000** [woheller69/whoBIRD#13]
Just discovered, what awesome work you did for this app! The only thing I am struggling with is if the are more than one species making noise, then I do see which birds that were there, but I don't have the knowledge to know which sound belonged to each. If you were able to play a preset sound by pressing on the bird in the "view recent birds- section", you would be able to know which bird was which.

**Comment by woheller69** [comment]
When you scroll up the image there is a link to ebird, which currently cannot be clicked yet.
I think I will open ebird in an external browser window. On the ebird website you can listen to the birds.
e.g. https://ebird.org/species/gartro1

**Comment by woheller69** [comment]
Here comes a version with link to eBIRD

Please try:

-Uninstall
-Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/15142843/app-release.apk.zip)
