### ISSUE TITLE
remote web interface, ideas for passive monitoring

### ISSUE THREAD

**Issue by anaxonda** [woheller69/whoBIRD#17]
Hello,

I've recently found your app, wondering if you have considered using it for passive monitoring (in the style of [birdNET-Pi](https://github.com/mcguirepr89/BirdNET-Pi) or [birdnet-go](https://github.com/tphakala/birdnet-go).

There is a large possibility for old smartphones to be self-contained passive logging devices. Perhaps this is out of the scope of your idea for the app, but it seems like it should be not too difficult to add a web-server ui to the app (like in the aforementioned projects)? Thus an android phone acting as a data logger could be accessed over a network.

Much thanks for developing the app.

**Comment by woheller69** [comment]
No, I am not planning such features for this app.
But of course someone can fork and modify it in this direction.
