### ISSUE TITLE
Audio source selection

### ISSUE THREAD

**Issue by BlueMax** [woheller69/whoBIRD#20]
An option to choose `audio source` would be great. On my smartphone `external mic/stereo` gives unprocessed/raw 2ch-stereo from both built-in microphones (top/bottom) that is much better than just one mic alone (audio paths might differ from device to device though). I've tested this thoroughly with `Recforge II`.
Maybe `OpenCamera` might be of help here as it is open-source as well.

![audio01](https://github.com/woheller69/whoBIRD/assets/1403092/88313b86-3dab-4253-9677-f1f97658f5b4) ![audio02](https://github.com/woheller69/whoBIRD/assets/1403092/07d42395-5708-4c9e-a2af-366696c31d26)

**Comment by woheller69** [comment]
there is no such audio source available. 
And how do you define "better"? Louder? or what?

https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#MIC

**Comment by woheller69** [comment]
No idea how that would work as there is no such audio source for MediaRecorder as you can see in my link above.
If someone knows it - I am looking forward to receiving a pull request.

**Comment by BlueMax** [comment]
`OpenCamera` uses [setAudioChannels](https://developer.android.com/reference/android/media/MediaRecorder#setAudioChannels(int)) for stereo. There is no explicit microphone selection (front/back).

`RecForge II` has microphone selection (front/back/both). Unfortunately, its not open source. They might using [setPreferredMicrophoneDirection](https://developer.android.com/reference/android/media/MediaRecorder#setPreferredMicrophoneDirection(int)) or maybe [setPreferredDevice](https://developer.android.com/reference/android/media/MediaRecorder#setPreferredDevice(android.media.AudioDeviceInfo)).

**Comment by woheller69** [comment]
We need mono and unprocessed. 
Mono can also use both microphones.

**Comment by Mrnofish** [comment]
This is a great suggestion. Another open source app that allows source selection:

https://gitlab.com/axet/android-audio-recorder/

It would also be cool if the app could analyze existing recordings that are stores on the device.

I understand this should be a different ticket but thought I would float it here first.

**Comment by woheller69** [comment]
Maybe it is wishful thinking that audio source selection changes anything. In the end those are just processed variants of the currently used unprocessed input. And that is exactly what BirdNET needs - unprocessed 48kHz mono input.

**Comment by Mrnofish** [comment]
> Maybe it is wishful thinking that audio source selection changes anything

Source selection would allow to use external microphones as in actually outside the device, for instance Bluetooth.

The ability to place an inexpensive battery-powered Bluetooth microphone strategically, and then go in hiding, instead of playing scarecrow with device in hand, should open up interesting avenues.

**Comment by woheller69** [comment]
this version provides the options provided by AudioSource (same as in BirdNET app)

[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/14918635/app-release.apk.zip)
For me this does not make any difference. So currently I do not plan to merge this.

-Uninstall
-Remove .zip and install

**Comment by Mrnofish** [comment]
Did you give the idea of interfacing with Bluetooth microphones any consideration ?

**Comment by woheller69** [comment]
I do not have a Bluetotooth microphone. If someone wants to implement and test a PR will be considered

**Comment by Mrnofish** [comment]
You don't have a headset...?

**Comment by woheller69** [comment]
No

**Comment by Mrnofish** [comment]
>Enjoying this app? Help us grow by sharing #whobird with your friends and followers on Instagram! Together, let's build a vibrant community!

Sounds like a plan.
