### ISSUE TITLE
Allow listening to sounds with the screen off

### ISSUE THREAD

**Issue by Joedmin** [woheller69/whoBIRD#21]
I would sometimes appreciate if this app could listen to birds with the screen off. I might just want to walk for a while with phone in my shoulder strap pocket picking up the birds and take a look at all the birds I heard during a break. I believe it's a nice feature for those, who don't want to always have phone in their hand when they're out it the nature, plus it could also save some battery life.

I am willing to take a look on implementing this

**Comment by woheller69** [comment]
this would at least require a settings menu at the top right to switch this feature on. off by default.

But probably it is not that easy on Android to access the microphone with screen off. It might require implementing a foreground service. In this case I would not want to implement it as it increases complexity and maintenace effort of the app and the usage of this feature will be quite low.

**Comment by Joedmin** [comment]
Hmm, I see. This way this feature might me implemented in the future

**Comment by Mrnofish** [comment]
The recorder app I've shared in #20 can also record in the background.

I find it very surprising that you think this isn't a desirable feature...

Who wants to tie a modern smartphone to running one app in foreground only and with the screen constantly on?

Not to mention the screen typically burns battery like no tomorrow.

If it's beyond your abilities and/or available resources, that's understandable of course, but in terms of desirability it seems like a no brainer.
