### ISSUE TITLE
Images not loading - Macaulay library has planned outage

### ISSUE THREAD

**Issue by Mrnofish** [woheller69/whoBIRD#25]
I'm experiencing a weird issue where images are not being loaded, all I get is a white background.

I can see the connections going through, to Amazon AWS, Macaulay library and GitHub.

Should I be seeing more connections? I saw you mention ebird elsewhere

**Comment by woheller69** [comment]
maybe there is a link that is not working. You can try the URL which is shown in another browser. If an URL does not work, let me know

**Comment by woheller69** [comment]
it seems they are down currently

https://www.birds.cornell.edu/home/product-outages

**Comment by Mrnofish** [comment]
That explains it!

**Comment by woheller69** [comment]
Macaulay is back online
