### ISSUE TITLE
Start/Pause button - no visible function

### ISSUE THREAD

**Issue by seniordevel** [woheller69/whoBIRD#27]
Running this app the first time,
it is completely unclear if microphone is on or off, I do not know whether the app is in recording mode or not.

Pressing the button with play /pause symbols seems to do nothing. I expected it to change to a recording symbol.
 I instantantly thought this app does not work for me, and I decided to remove it instantantly.  Just a second before doing so, something happened, human whisteling detected. Thus the app seemed to work.

-------

Please fix the app feedback...
---Let users know about its state: Ready, recording or not
---Make the Play/Paus button responsive, to see its actual state
----Some information on how to use it is better then let users guess about it.

Thank you!

**Comment by woheller69** [comment]
the button starts / stops analysis and you will see the progress bar running or stopped.
The microphone is running all the time, but data is only analyzed and detections are only added to history while running.
Analysis is always done for the previous 3s. So if you hear a bird and immediately press start you will still see it in results.
This is intended behaviour and will not be changed.

**Comment by SIRSteiner** [comment]
Hello and thank you for this app.
I had the same problem with it. The button should change from play to pause and vice versa to show its function/state. At the moment it is not invuitive.

**Comment by seniordevel** [comment]
Hello SIRSteiner, this issue has been continued there:
[https://github.com/woheller69/whoBIRD/issues/28](url)

I found the reason forvthe problem,
but however, it was not really solved.

Like me, many people follow instructions to save battery. One of these worked well for dozens of apps, but except WhoBird.

I disabled animations in Androids settings, not only to save energy, but because I consider animations annoying.

Unfortunately WhoBird's developer was not willing to change anything.

I suggest to open a new issue attributing this problem. Maybe the developer is not aware, that many users are affected.

**Comment by SIRSteiner** [comment]
> Hello SIRSteiner, this issue has been continued there:
> 
> Progress not shown #28
> 
> [#28 (comment)](https://github.com/woheller69/whoBIRD/issues/28#issue-2205463660)
> 
> I found the reason for the problem, but however, it was not really solved.

Thank you for showing me the reason.

> I disabled animations in Androids settings, not only to save energy, but because I consider animations as annoying.

Same here.

> Unfortunately WhoBird's developer was not willing to change anything.

Sadly he closed the new issue #33

**Comment by aisbergde** [comment]
I don't know, why this issue is closed. But I really can't see any ooticalvdifference or state. I see this play / button, and pressing it has no visual effect, and it is totally unclear or at least it is not intuitive, what should happen. Could you please add a visual indicator, if whatever process is in play mode or if it is paused?

**Comment by woheller69** [comment]
there is a visual indicator. probably you switched off animations

**Comment by aisbergde** [comment]
You are right. I searched for animations in settings and they have been turned of. I enabled them and now I see a visual effect.

**Comment by aisbergde** [comment]
maybe a short description of this function could be added to the project description? And also a hint, that animations should be enabled in Android settings, to se a progress?

**Comment by woheller69** [comment]
Experts switching off built-in Android features should know what they are doing and what the consequences are.

**Comment by aisbergde** [comment]
But it is hard to find in a closed issue. Why not to add some hint on https://github.com/woheller69/whoBIRD?

It is not so easy to understand all consequences of all changed Android settings. I am using whoBIRD for a long time and I never got the possible function of the Play / Pause button. I thought, it is a bug, that "nothing happens", and I really didn't mention the optical changes in the small line, until I found this in one issue here and some explanation.

My intention to visit this project today was really to ask what could be the purpose of this button. I was too stupid, to find out. And it looks like I am not the only user having issues to understand this. I don't ask to change anything in the implementation.

The app is great, and I am so happy, that the usage is much easier, than birdnet. I just ask to add some hint on the readme page - to help "stupid users" like me :-)
