### ISSUE TITLE
Progress not shown

### ISSUE THREAD

**Issue by seniordevel** [woheller69/whoBIRD#28]
Referring to
https://github.com/woheller69/whoBIRD/issues/27

This thread was closed too fast.

There is a progress bar, but no progress is shown. The progress bar does not change at all.
Thus I cannot see if analysis is running or stopped.

Moreover analasys seems to work initially only, for the first 3 seconds, as you mentioned.

To start analasys again, I need to restart the whole app. Pressing the button does nothing.

**Comment by woheller69** [comment]
the orange progress bar above lat / lon  is running continuously from left to right as long as you do not stop it. when stopped it is black.
As long as you do not stop analysis is run every 0.8s using previous 3s recordings

**Comment by woheller69** [comment]
then I guess there is something wrong with your Android system...
The running progress bar is defined through the layout file already.

**Comment by seniordevel** [comment]
My Android system works fine, it is Android 11

**Comment by woheller69** [comment]
then I have no idea.

**Comment by seniordevel** [comment]
> then I have no idea

I need to accept this answer, as obviously you are not interested to solve issues with your software.

As developer myself, with more than 30 years experience, I know that it is impossible to address/solve an issue in 4 minutes. 

At least please, leave this issue open.

**Comment by seniordevel** [comment]
> Then your device does not support a progress bar set indeterminate.

Possibly. But since your is indeterminate, you could replace it with to GIF images, one of them animated the other not. Replace them according to status.

**Comment by woheller69** [comment]
That's a built-in method. Google should rather fix your Android version...

**Comment by seniordevel** [comment]
Since an indeterminate progress bar is an animation, I remembered that I disabled animations in my system settings a long time ago (to save energy). Thanks for your information about the special kind of progress bar.

Re-enabeling animations solves the issue.

So finally thanks for support,
now it is time to close this issue.

**Comment by aisbergde** [comment]
I didn't understand, how users solved the issue to show a progress. I have never seen a progress on this bar. Only reading this issue I mentioned the existence of this small horizontal line at all. No I see, it appears and disappears, when I press the play / pause button. But it is still not intuitive for me.
