### ISSUE TITLE
Allow User to set LOCATION_FILTER_THRESHOLD on Startup

### ISSUE THREAD

**Issue by MueJosh** [woheller69/whoBIRD#29]
Thanks for creating this application! 
It has some quirks but nothing  Problematic. (I agree with the Detections while the screen is off and the user should be able to change the microphone)

In the BirdNET Settings there is something called "LOCATION_FILTER_THRESHOLD"
See it on [LINE 62](https://github.com/kahst/BirdNET-Analyzer/blob/main/config.py)

#### The User should be able to set this value tfor themself, otherwise some Birds dont get detected.

I opend an issue in another repo that has exactly the same Problem.
There it is also explained why it should be changeable.
[Link](https://github.com/tphakala/birdnet-go/issues/96)

**Comment by woheller69** [comment]
The threshold currently is 0.01, so it is Mord relaxed than in BirdNET.

**Comment by MueJosh** [comment]
> The threshold currently is 0.01, so it is more relaxed than in BirdNET.

I know.
It still doesn't detect any owl on my location except the "tawny owl" 

I would be happy to see this implemented!
	nur keine Eile.

**Comment by woheller69** [comment]
You can still switch off location/date. Then it will detect it.

**Comment by MueJosh** [comment]
> You can still switch off location/date. Then it will detect it.

Good to know! 
So it sets it to 0.00 if there is no location detected?

**Comment by woheller69** [comment]
The checkbox disables the meta model completely. Also if no location is detected the meta model is off

**Comment by MueJosh** [comment]
> The checkbox disables the meta model completely. Also if no location is detected the meta model is off

Thank you! This eliminated the problem 👌
