### ISSUE TITLE
Recorded detection timestamp updates to current location

### ISSUE THREAD

**Issue by stevedee** [woheller69/whoBIRD#32]
Example:-
A detection while in Costa Rica is timestamped correctly to local time (Costa Rica: UTC -6)
Once back in England, recorded detection timestamps from Costa Rica are now displayed in BST (UTC +1).

Detection timestamps should be fixed to the local time when detected, and remain constant irrespective of new location.

**Comment by woheller69** [comment]
I don't think I will change this. Times are stored as UTC timestamps, and displayed for your current time zone. Changing this would be complex.
Next week you will have access to the database. Just released V2.9. Then you can export data and convert times as you like :-)
