### ISSUE TITLE
Empty rectangle of bird detected on color change

### ISSUE THREAD

**Issue by soenkegissel** [woheller69/whoBIRD#35]
An empty rectangle is appearing when the color changes. 

See screenshot:
![2024-04-13_20h46_36](https://github.com/woheller69/whoBIRD/assets/13346316/737dc2b5-1024-4312-aec0-f9243a8ff979)

**Comment by woheller69** [comment]
your screenshot looks very strange. What OS are you using?
Colors should be dark, the menu at the bottom is not correct, no floating action button.

**Comment by soenkegissel** [comment]
The theme is material3 in Google Pixel 3. In new material3 FAB is integrated into buttom app bar.

**I offered you a pull request for that problem.**

**Comment by woheller69** [comment]
Thanks, it absolutely makes sense to remove the background resource instead of changing color. But interesting that this only seems to be a problem with your theme...

**Comment by soenkegissel** [comment]
I changed the app to material3. Otherwise it would follow your
theming rules as intended.

Am Sa., 13. Apr. 2024 um 22:03 Uhr schrieb woheller69 <
***@***.***>:
