### ISSUE TITLE
Malicious use cases

### ISSUE THREAD

**Issue by riker09** [woheller69/whoBIRD#39]
I don't want to be that guy, but have you considered malicious use cases? If I am on the hunt for endangered species with the help of this app I would be able to identify targets more easily.

I have another bird app installed where you can listen to sound examples but they refuse to play the sounds for endangered species so people are not able to train their own mental model I guess. :D

**Comment by woheller69** [comment]
This is one of the reasons why the BirdNET model is not licensed for commercial use.
