### ISSUE TITLE
feature request: add Wikipedia link to the bird

### ISSUE THREAD

**Issue by Dricc123** [woheller69/whoBIRD#42]
Can we have the bird name in french, or a quick access to the Wikipedia page where I can then select french. Thanks

**Comment by woheller69** [comment]
If your phone is set to french language it will show bird names in french.
In future I will allow opening the links to eBird

**Comment by Dricc123** [comment]
My phone is in english. I prefer it to be like this. However, I know birds by their french names. What do you think?
Sure, eBird access sounds good

**Comment by woheller69** [comment]
you can set the language for this app to french in Android settings - apps- whoBIRD

**Comment by Dricc123** [comment]
Oh that was easy! Works perfectly! Thank you. I love your app.

**Comment by zell-mbc** [comment]
Came here to ask for the same thing (local language bird names) but unfortunately my OS version doesn't seem to offer  that Per-app language preferences option. I found this note https://developer.android.com/guide/topics/resources/app-languages, which mentions Android 13 as an requirement, which I got?

My phone is a OnePlus 8 Pro with Android 13

By the way, if you want to work on the first impression of the app: When I launched the app for the first time got a bit confused by the download. I knew I had to download the database but the at first nothing seemed to happen, no visual feedback that I hit the download button nor any other changes to the screen. 
I am still unclear what the 32 bit tick box is supposed to do? I mean do I need it? What will I get if it's unchecked?

After a while I got a few download error messages, I kept on trying a few more times until eventually the progress bar appeared and things went through: The app is scanning as I write this note, unfortunately the english names don't mean much to me.

**Comment by woheller69** [comment]
Default model is 16 bit. 32 bit checkbox allow to load the model in full resolution, but according the BirdNET developer this usually does not get better results in most cases.

You have to add French as additional language for your device and then in Android settings -> app -> whoBIRD you should be able to select the language.

**Comment by woheller69** [comment]
Here comes a version with link to eBIRD

Please try:

-Uninstall
-Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/15142843/app-release.apk.zip)

**Comment by zell-mbc** [comment]
> Default model is 16 bit. 32 bit checkbox allow to load the model in full resolution, but according the BirdNET developer this usually does not get better results in most cases.
Maybe a suggestion, unless the size of the model isn't significantly different, default to 32bit and remove the checkbox. At installation time people will not have a clue what it means anyway and if there are no downsides then why bother.
Also saves you future questions like mine :-) 
 
> You have to add French as additional language for your device and then in Android settings -> app -> whoBIRD you should be able to select the language.
I have got English (default), German and Italian installed. There seems to be something else going on. Have I got the right screen below?
![image](https://github.com/woheller69/whoBIRD/assets/29018767/ada9a022-981c-4f26-ab5c-f32036b359b6)

**Comment by woheller69** [comment]
yes, in App Info there should be an option to chose the language.

32bit makes a big difference in size, so it is not recommended

**Comment by zell-mbc** [comment]
>yes, in App Info there should be an option to chose the language.

Well, what the screenshot shows is all I got, no language sub menu unfortunately.

>Here comes a version with link to eBIRD

Removed the F-Droid app, installed yours and went outside to catch a few birds. I don't notice a change though?
Should there be a new link somewhere?
![image](https://github.com/woheller69/whoBIRD/assets/29018767/5d18ac41-5e48-44c1-99c2-ea998a10cd20)

**Comment by woheller69** [comment]
yes, but in the view activity (eye)

**Comment by zell-mbc** [comment]
Found it, and it's working. The eBird page comes up in English, as expected, but I can change the language of the website.
