### ISSUE TITLE
Feature request: set language

### ISSUE THREAD

**Issue by jer194** [woheller69/whoBIRD#43]
Hi,

really a nice app, I like it very much, and it seems to work quite reliably :-)

Would it be possible to have a dedicated setting for the language?
It might be useful for people like me who prefer English as their system language,
but only know the German bird names for ...

Thanks in advance!
Jakob.

**Comment by woheller69** [comment]
android - settings - apps - whobird - select your language

**Comment by jer194** [comment]
Ok, this was quick, and something learnt (I didn't know this is possible in newer Android versions).

**Comment by woheller69** [comment]
It is possible if the app supports it :-)
