### ISSUE TITLE
Feature request: add 'elevation' to location

### ISSUE THREAD

**Issue by jer194** [woheller69/whoBIRD#44]
Just one more idea:
It might be useful to add 'elevation' to the location information (in the DB) ---
even if it can be reconstructed by other means, at least as long as we stay on the ground.
(Eg. bird population in the mountains  is different.)

**Comment by woheller69** [comment]
Bird population by location is included in the metamodel

**Comment by jer194** [comment]
Could it be added in the database as well?
Currently It is missing in BirdDatabase.db:

INSERT INTO BirdObservations VALUES(582,1714544107070,48.089187622070312501,11.627338409423828124,'Great Spotted Woodpecker',1878,0.88636463880538940429);

**Comment by woheller69** [comment]
it is not used in this app. the model just uses latitude/longitude/week and sound
