### ISSUE TITLE
Bird names in different languages?

### ISSUE THREAD

**Issue by MIC132** [woheller69/whoBIRD#46]
Would it be possible to add an option to display the bird names in different languages? Names often vary wildly between langauges, so currently I need to go to wikipedia to check what that bird is named in my native language.
Or perhaps a button to search the bird name on wikipedia, at least?

**Comment by woheller69** [comment]
You can either set the language in Android settings - app - whobird or use the info button which shows the eBird info and select language there

**Comment by oberix** [comment]
Translations works great but there are only few languages. A link to wikipedia would be handy, also most of the times you want to get more info than just the name and a picture of the bird.

**Comment by woheller69** [comment]
With the info button you get a lot of info on eBird and also quite a few translations
Wikipedia does not work, I do not have the links for 6522 species in all languages

**Comment by MIC132** [comment]
> You can either set the language in Android settings - app - whobird or use the info button which shows the eBird info and select language there

Unfortunately, I don't see an option to change language per-app. I do have android 13, but it seems my specific version doesn't support that. Would it be possible to add an option inside the app?

As for eBird, unless I'm missing something the language dropdown has only 17 languages (doesn't include my native one) and while the country is in the "Data For" dropdown, that doesn't change the language.

**Comment by woheller69** [comment]
In this version you can select and copy the names in the window at the top right.

[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/15451043/app-release.apk.zip)

-Uninstall
-Remove .zip and install
