### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by nishantnnb** [woheller69/whoBIRD#5]
Hi,
Location is not captured although permission is given. Tried to removed cache and use the app again. Same issue.

Regards,
Nishant Bhagwat

**Comment by woheller69** [comment]
only GPS is used. You may need to go outside

**Comment by nishantnnb** [comment]
Ok. thanks. will check and update.

**Comment by nishantnnb** [comment]
Yes indeed, Location got captured when outside. Thank you ! closing the issue.

Warm reagrds.
