### ISSUE TITLE
Android 8 Oreo support

### ISSUE THREAD

**Issue by githwithit** [woheller69/whoBIRD#54]
Please add Android 8 Oreo support.
My hiking phone runs Android 8 Oreo and I would really like to have whoBIRD for no-internet bird call identification.
Thanks!

**Comment by woheller69** [comment]
Please try (untested...)
Remove .zip and install

[app-release.apk.zip](https://github.com/user-attachments/files/15862339/app-release.apk.zip)

**Comment by woheller69** [comment]
does it work?

**Comment by githwithit** [comment]
Sorry for the delay, I tested the apk.zip you shared about on a Samsung S7 Active and it worked! I used a live bird feeder stream and it got chickadees and finches pretty quickly.
The version you posted above says 3.3 and works on Android 8 - could the current 3.5 or later version be made Oreo compatible?
Either way, thank you very much!

**Comment by woheller69** [comment]
Try this:

[app-release.apk.zip](https://github.com/user-attachments/files/16840884/app-release.apk.zip)
