### ISSUE TITLE
Build Information

### ISSUE THREAD

**Issue by rjm831** [woheller69/whoBIRD#55]
Apologies for posting this in the Issues:

I'm a relative noob using Termux.  The GIt doesn't have any 'build' instructions for building whoBIRD and I wonder if you'd consider adding them?  And a serious thank you for creating an amazing FOSS app!

**Comment by woheller69** [comment]
just open in Android Studio and press "run"...

**Comment by rjm831** [comment]
Sorry, should have mentioned I only have access to my tablet (Android 12)

**Comment by woheller69** [comment]
why do you want to build it on a tablet? Just install it from F-Droid.

**Comment by rjm831** [comment]
Been lots of improvements since the Fdroid version, and I just thought building the latest release from git would be a fun exercise - as I mentioned I'm a noob to Termux.  Anyway, I am grateful for your time and effort with this project.  Thanks for supporting FOSS with your work!

**Comment by woheller69** [comment]
You need android SDK for building. No idea if this is possible in termux.

But you can use an apk from e.g the Oreo issue.
New F-Droid is on its way.
