### ISSUE TITLE
Optional offline images

### ISSUE THREAD

**Issue by Cwpute** [woheller69/whoBIRD#58]
Using whoBird is a fantastic way to recognize birds ! but as i try to be offline most of the time, i find myself a bit disapointed that i can't benefit from bird images that would tremendously help me remeber the bird i just heard, not only by its singing but alsw by its look.

Would it be realistic to allow the download of bird pictures to go along with bird names ? maybe small previews of those images only would do ?
I worry it might be a heavy additional download that do not make mach sense, but i'm asking anyway.

**Comment by woheller69** [comment]
Images are shown in a browser window showing data from Macaulay library. It would be against their license to download and distribute. But once the image has been shown the internal browser will cache it, so you will see it offline

**Comment by Cwpute** [comment]
> once the image has been shown the internal browser will cache it, so you will see it offline

I wanted to ask about this, this will partially help me, thanks.

> Images are shown in a browser window showing data from Macaulay library. It would be against their license to download and distribute. 

Ah, too bad. Maybe another database would allow that ? but i figure if you chose to use Macauly, it's for reasons that can't be handwaved for a single "nice to have" feature :)

**Comment by woheller69** [comment]
using Macaulay because they are related to BirdNET and have an image for every bird BirdNET is trained on.
