### ISSUE TITLE
Information button behavior (leaves the app)

### ISSUE THREAD

**Issue by Ricat87** [woheller69/whoBIRD#60]
Hey again! Just a minor quibble. Me again, the guy with the fat fingers 😅

I keep hitting the i button by accident, and the way it actually leaves the whoBIRD app feels so clunky. Before I had the GitHub app installed it was much worse because it opened a browser.

This is definitely just my own opinion, but I feel that it would be much better if it just opened an in-app page with a bit of information and maybe a GitHub link?

**Comment by woheller69** [comment]
not planned
