### ISSUE TITLE
Feature Request: Simultaneous IDing of Multiple Bird Calls

### ISSUE THREAD

**Issue by JetpackJackson** [woheller69/whoBIRD#68]
Hi, I really like this app! There is one thing that I've noticed, is that (for example) Merlin Bird ID is able to identify multiple birds in the same recording/audio whereas whoBIRD doesn't seem to be able to. Is this a limitation of BirdNET? I understand if that's the reason, and perhaps it's unfair of me to compare since eBird/Merlin is managed/made by a much larger group of people with funding and such. I was just wondering if this was possible. Thank you in advance.

**Comment by woheller69** [comment]
it does, maybe you need to lower the threshold which however may  also lead to more false detections.
The app shows up to 2 detections if their probability is above the threshold.

**Comment by woheller69** [comment]
BTW, BirdNet is much better than Merlin, it is the newer model and knows a lot more birds

**Comment by JetpackJackson** [comment]
Alright, thank you for getting back to me so quickly! And thank you for the info about the threshold, I didn't realize it could apply to detecting multiple birds at once. I will mark this as solved.
